name: CICD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run:  echo "The job was automatically triggered by a ${{ github.event_name }} event for repository ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build .
      - name: Run vet & golint
        run: |
          go vet .
          golint .
      - run: echo "This job's status is ${{ job.status }}."
